version: '2.1'

services:

  mail-service:
    image: ${DOCKER_IMAGE}
    command: >
      ./start-app.sh
    ports:
    - "8080:8080"
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      skynet:
        aliases:
        - "mail-service"
    environment:
      JAVA_OPTS: -Dlogback.configurationFile=logback-dev.xml
      HOST_ADDRESS: ${HOST_ADDRESS}
      JAR_NAME: ${JAR_NAME}

  kafka:
    image: landoop/fast-data-dev:2.1.0
    ports:
    - "9092:9092"
    - "3030:3030"
    networks:
      skynet:
        aliases:
        - kafka
    environment:
      ADV_HOST: ${HOST_ADDRESS}
      SAMPLEDATA: 0
      CONNECT_HEAP: 1G
      RUNTESTS: 0
      DISABLE_JMX: 1
      BROWSECONFIGS: 1
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test: >
        sleep 20
      interval: 3s
      timeout: 25s

networks:
  skynet:
