version: '2.1'

services:

  mail-api:
    image: ${DOCKER_IMAGE}
    command: >
      ./start-app.sh -s API
    ports:
    - "8080:8080"
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      skynet:
        aliases:
        - "mail-api"
    environment:
      JAVA_OPTS: -Dlogback.configurationFile=logback-dev.xml
      HOST_ADDRESS: ${HOST_ADDRESS}
      JAR_NAME: ${JAR_NAME}
      PORT: 8080

  send-mail-service:
    image: ${DOCKER_IMAGE}
    command: >
      ./start-app.sh -s SEND_MAIL
    ports:
    - "8081:8081"
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      skynet:
        aliases:
        - "send-mail-service"
    environment:
      JAVA_OPTS: -Dlogback.configurationFile=logback-dev.xml
      HOST_ADDRESS: ${HOST_ADDRESS}
      JAR_NAME: ${JAR_NAME}
      PORT: 8081

  kafka:
    image: landoop/fast-data-dev:2.1.0
    ports:
    - "9092:9092"
    - "3030:3030"
    networks:
      skynet:
        aliases:
        - kafka
    environment:
      ADV_HOST: ${HOST_ADDRESS}
      SAMPLEDATA: 0
      CONNECT_HEAP: 1G
      RUNTESTS: 0
      DISABLE_JMX: 1
      BROWSECONFIGS: 1
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test: >
        sleep 20
      interval: 3s
      timeout: 25s

  fakesmtp:
    image: reachfive/fake-smtp-server:latest
    ports:
    - "1025:1025"
    - "1080:1080"

networks:
  skynet:
